### ISSUE TITLE
`if` parameter is pretty broken

### ISSUE THREAD

**Issue by XXiaoA** [XXiaoA/xdm#1]
has bug now if work wrong if has relative path

For example:
```yaml
link:
  1:
    path: 2
    If: test -e /usr/bin/ls
```
